import {
  WEBSOCKET_BROKEN,
  WEBSOCKET_CLOSED,
  WEBSOCKET_CONNECT,
  WEBSOCKET_DISCONNECT,
  WEBSOCKET_MESSAGE,
  WEBSOCKET_OPEN,
  WEBSOCKET_SEND,
} from '@giantmachines/redux-websocket';

export const HP_WEBSOCKET_PREFIX = 'HP_REDUX_WEBSOCKET';

export const HP_REDUX_WEBSOCKET_BROKEN = `${HP_WEBSOCKET_PREFIX}::${WEBSOCKET_BROKEN}`;
export const HP_REDUX_WEBSOCKET_OPEN = `${HP_WEBSOCKET_PREFIX}::${WEBSOCKET_OPEN}`;
export const HP_REDUX_WEBSOCKET_CLOSED = `${HP_WEBSOCKET_PREFIX}::${WEBSOCKET_CLOSED}`;
export const HP_REDUX_WEBSOCKET_MESSAGE = `${HP_WEBSOCKET_PREFIX}::${WEBSOCKET_MESSAGE}`;
export const HP_REDUX_WEBSOCKET_CONNECT = `${HP_WEBSOCKET_PREFIX}::${WEBSOCKET_CONNECT}`;
export const HP_REDUX_WEBSOCKET_DISCONNECT = `${HP_WEBSOCKET_PREFIX}::${WEBSOCKET_DISCONNECT}`;
export const HP_REDUX_WEBSOCKET_SEND = `${HP_WEBSOCKET_PREFIX}::${WEBSOCKET_SEND}`;
